/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Cartelera;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import Clases.Validaciones;
import javax.swing.JOptionPane;

public class Eliminar_cartelera extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar_cartelera
     */
    public Eliminar_cartelera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setBackground(new java.awt.Color(247, 247, 247));
        Tabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tabla.setForeground(new java.awt.Color(0, 51, 153));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo de pelicula", "Fecha Estreno", "Genero", "Clasificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 680, 219));

        jLabel10.setFont(new java.awt.Font("Copperplate", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("SELECCIONE UN CAMPO PARA BUSCAR LA CARTELERA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 360, 60));

        jLabel14.setFont(new java.awt.Font("Copperplate", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("ID DE CARTELERA A ELIMINAR");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 216, 40));

        jTextField2.setText(" ");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 110, 30));

        jLabel12.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel12.setText("ID:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, 30));

        Eliminar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(0, 0, 255));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/basura.png"))); // NOI18N
        Eliminar.setToolTipText("Eliminar");
        Eliminar.setBorder(null);
        Eliminar.setBorderPainted(false);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 30, 30));

        Buscar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Buscar.setForeground(new java.awt.Color(0, 0, 255));
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lupa.png"))); // NOI18N
        Buscar.setToolTipText("Buscar");
        Buscar.setBorder(null);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 30, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un campo:", "Ver todos", "ID", "Fecha de estreno" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 87, 170, 30));

        jLabel13.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel13.setText("Filtro:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 86, -1, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deshacer.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 59, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
 ObjectContainer Basep = Db4o.openFile(Inicio.direccionBD);
       Eliminar_Cliente(Basep);
        Cerrar_BD(Basep);

    }//GEN-LAST:event_EliminarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

        ObjectContainer Basep = Db4o.openFile(Inicio.direccionBD);
       Buscar_ClienteCedula(Basep);
        Cerrar_BD(Basep);
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Inicio ecar = new Inicio ();
        ecar.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void Buscar_ClienteCedula(ObjectContainer basep) {

        if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selección invalida");

        } else {
            if (jComboBox1.getSelectedIndex() == 1) {

        Cartelera Clbuscar = new Cartelera(null, null, null, null, null, 0, 0, 0);

                ObjectSet result = basep.get(Clbuscar);
                MostrarDatos(result);
            } else {
                if (jComboBox1.getSelectedIndex() == 2) {

                    String IDAux = JOptionPane.showInputDialog("Ingrese la Cedula a consultar");

        Cartelera Clbuscar = new Cartelera(IDAux, null, null, null, null, 0, 0, 0);

                    ObjectSet result = basep.get(Clbuscar);
                    MostrarDatos(result);

                } else {
                    if (jComboBox1.getSelectedIndex() == 3) {
                        String IDAux = JOptionPane.showInputDialog("Ingrese la Cedula a consultar");

                         Cartelera Clbuscar = new Cartelera(null, null, IDAux, null, null, 0, 0, 0);

                    ObjectSet result = basep.get(Clbuscar);
                    MostrarDatos(result);
                    }
                }
            }
        }

        //Borrar la eleccion y ponerla al inicio
        jComboBox1.setSelectedIndex(0);
    }
    
    public void MostrarDatos(ObjectSet result) {
        String matrizcliente[][] = new String[result.size()][5];

        if (result.size() == 0) {
            JOptionPane.showMessageDialog(null, "La pelicula no se encuentra en la base de datos");
        } else {
            for (int i = 0; i < result.size(); i++) {

                Cartelera miCl = new Cartelera();

                miCl = (Cartelera) result.get(i);
                matrizcliente[i][0] = miCl.getCod_Cartelera();
                matrizcliente[i][1] = miCl.getTitulo_pelicula();
                matrizcliente[i][2] = miCl.getGenero();               
                matrizcliente[i][3] = miCl.getClasificacion();
                matrizcliente[i][4] =  String.valueOf(miCl.getFecha_estreno());
              

                Tabla.setModel(new javax.swing.table.DefaultTableModel(matrizcliente, new String[]{"Codigo", "Titulo", "Genero", "Clasidicacion", "Fecha Estreno"}));

            }
        }

    }
    
    public void Eliminar_Cliente(ObjectContainer basep) {

        Registro_Cliente Clinterfaz = new Registro_Cliente();//Crear un objeto de la clase Estudiantes para traer el metodo Comprobar_Estudiantes

        if (jTextField2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cedula no valido");
        } else {

            String IDE = jTextField2.getText();
        Cartelera Cleliminar = new Cartelera(null, null, null, null, null, 0, 0, 0);
            ObjectSet result = basep.get(Cleliminar);

            if (Clinterfaz.Comprobar_Cliente(basep, IDE) == 0) {

                JOptionPane.showMessageDialog(null, "El cliente no existe en la base de datos");

            } else {
                Cartelera Clienteeliminar = (Cartelera) result.next();

                basep.delete(Clienteeliminar);
                JOptionPane.showMessageDialog(null, "El Cliente fue eliminado de la base de datos exitosamente");
            }

        }

        //Borrar el campo de texto
        jTextField2.setText("");
    }

    public void Cerrar_BD(ObjectContainer basep) {

        basep.close();
    }
            
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
