/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.Cliente;
import static Ventanas.Modificar_pelicula.Cerrar_BD;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;


/**
 *
 * @author EDU
 */
public class Modificar_cliente extends javax.swing.JFrame {
    
    String cedula = "";
    String nombre = "";
    String direccion = "";
    String edad = "";
    String fecha_nacimiento = "";
    String telefono_cli = "";
    String correo_cli = "";
    String membresia = "";
    int dia = 0;
    int mes = 0;
    int anio = 0;


    /**
     * Creates new form Modificar_cliente
     */
    public Modificar_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        correo_cli2 = new javax.swing.JTextField();
        telefono_cli2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cedula_cliente2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_cli2 = new javax.swing.JTextField();
        direccion_cli2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edad_cliente2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Modificar_cli = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dia_cli = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        mes_cli = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        anio_cli = new javax.swing.JSpinner();
        membresia_cliente2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/wallet_membership_icon_136040.png"))); // NOI18N
        jLabel9.setText("Membresia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/email.png"))); // NOI18N
        jLabel8.setText("Correo electronico");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));
        jPanel1.add(correo_cli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 189, -1));

        telefono_cli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_cli2ActionPerformed(evt);
            }
        });
        jPanel1.add(telefono_cli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 189, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/telefono.png"))); // NOI18N
        jLabel7.setText("Telefono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/date.png"))); // NOI18N
        jLabel6.setText("Fecha nacimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));
        jPanel1.add(cedula_cliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 149, -1));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cedula.png"))); // NOI18N
        jLabel1.setText("cedula");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 115, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nombre.png"))); // NOI18N
        jLabel2.setText("nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        nombre_cli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_cli2ActionPerformed(evt);
            }
        });
        jPanel1.add(nombre_cli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 149, -1));
        jPanel1.add(direccion_cli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 149, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ic_location_on_128_28437.png"))); // NOI18N
        jLabel3.setText("direccion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/age_theapplication_3019.png"))); // NOI18N
        jLabel5.setText("Edad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        edad_cliente2.setModel(new javax.swing.SpinnerNumberModel(18, 18, 80, 1));
        jPanel1.add(edad_cliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar_1.png"))); // NOI18N
        jLabel4.setText("MODIFICAR CLIENTE ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(101, 153, 169));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lupa.png"))); // NOI18N
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 29));

        Modificar_cli.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Modificar_cli.setForeground(new java.awt.Color(0, 0, 255));
        Modificar_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/girar.png"))); // NOI18N
        Modificar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_cliActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 30, 30));

        jLabel10.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel10.setText("MODIFICAR");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, 20));

        dia_cli.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel1.add(dia_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 10, -1));

        mes_cli.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        jPanel1.add(mes_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        anio_cli.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        jPanel1.add(anio_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        membresia_cliente2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "VIP sencilla", "Premium Sencilla", "Standard Sencilla", "VIP Doble", "Premium Doble", "Standard Doble" }));
        jPanel1.add(membresia_cliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefono_cli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_cli2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_cli2ActionPerformed

    private void nombre_cli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_cli2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_cli2ActionPerformed

    private void Modificar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_cliActionPerformed

        ObjectContainer BaseD = Db4o.openFile(Inicio.direccionBD);
        Modificar_Cliente(BaseD);
        Cerrar_BD(BaseD);
        cedula_cliente2.setEditable(true);
    }//GEN-LAST:event_Modificar_cliActionPerformed
 public void buscar(ObjectContainer basep) {//cargardatos

        Modificar_cli.setEnabled(false);
        String CODIGOAux;
        CODIGOAux = cedula_cliente2.getText();
        Registro_Cliente EAux = new Registro_Cliente();
        if (cedula_cliente2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una Cedula");
        } else {
            if (EAux.Comprobar_Cliente(basep, CODIGOAux) == 0) {
                JOptionPane.showMessageDialog(null, "El cliente no existe en la base de datos");
                LimpiarCamposTexto();
            } else {
                Cliente Clbuscar = new Cliente(null, null, null, cedula, null, null, null, null, 0, 0, 0);
                ObjectSet result = basep.get(Clbuscar);
                for (int i = 0; i < result.size(); i++) {
                    Cliente miCl = new Cliente();
                    miCl = (Cliente) result.get(i);
                    nombre_cli2.setText(miCl.getNombre());
                    direccion_cli2.setText(miCl.getDireccion());
                    telefono_cli2.setText(miCl.getTelefono_cli());
                    for (int j = 0; j < membresia_cliente2.getItemCount(); j++) {
                        if (miCl.getMembresia().equalsIgnoreCase(membresia_cliente2.getItemAt(j))) {
                            membresia_cliente2.setSelectedIndex(j);
                            j = membresia_cliente2.getItemCount();
                        }
                    }
                    correo_cli2.setText(miCl.getCorreo_cli());
                    dia_cli.setValue(miCl.getDia());
                    mes_cli.setValue(miCl.getMes());
                    anio_cli.setValue(miCl.getAnio());
                    edad_cliente2.setValue(miCl.getEdad());

                }

                HabilitarCampos_deTexto();
                cedula_cliente2.setEditable(false);
            }

        }
    }

    public static int Comprobar_Cliente(ObjectContainer basep, String cedula) {

        Cliente Clbuscar = new Cliente(null, null, null, cedula, null, null, null, null, 0, 0, 0);

        ObjectSet result = basep.get(Clbuscar);

        return result.size();
    }

    public void Modificar_Cliente(ObjectContainer basep) {

        JOptionPane.showMessageDialog(null, "Existen campos vacios");
        //LimpiarCamposdeTexto();

        Cliente Clmod = new Cliente(null, null, null, cedula_cliente2.getText(), null, null, null, null,0,0,0);
        ObjectSet result = basep.get(Clmod);
        Cliente Clmodificar = (Cliente) result.next();
        
        Clmodificar.setNombre(nombre_cli2.getText());
        Clmodificar.setDireccion(direccion_cli2.getText());
        Clmodificar.setTelefono_cli(telefono_cli2.getText());
        Clmodificar.setCorreo_cli(correo_cli2.getText());
        Clmodificar.setMembresia(membresia_cliente2.getSelectedItem().toString());
        Clmodificar.setEdad((String) edad_cliente2.getValue());
        Clmodificar.setDia((Integer) dia_cli.getValue());
        Clmodificar.setMes((Integer) mes_cli.getValue());
        Clmodificar.setAnio((Integer) anio_cli.getValue());

        basep.set(Clmodificar);
        JOptionPane.showMessageDialog(null, "El cliente fue modificado exitosamente");
        LimpiarCamposTexto();

    }

    public static void Cerrar_BD(ObjectContainer basep) {

        basep.close();
    }
     public void LimpiarCamposTexto() {
         cedula_cliente2.setText("");
        nombre_cli2.setText("");
        direccion_cli2.setText("");
        dia_cli.setValue(0);
        mes_cli.setValue(0);
        anio_cli.setValue(0);

        edad_cliente2.setValue(18);
        telefono_cli2.setText("");
        correo_cli2.setText("");
        membresia_cliente2.setSelectedIndex(0);
    }

    public void HabilitarCampos_deTexto() {
        cedula_cliente2.setEditable(true);
        nombre_cli2.setEditable(true);
        direccion_cli2.setEditable(true);
       
        telefono_cli2.setEditable(true);
        membresia_cliente2.setEditable(true);
        correo_cli2.setEditable(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar_cli;
    private javax.swing.JSpinner anio_cli;
    private javax.swing.JTextField cedula_cliente2;
    private javax.swing.JTextField correo_cli2;
    private javax.swing.JSpinner dia_cli;
    private javax.swing.JTextField direccion_cli2;
    private javax.swing.JSpinner edad_cliente2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> membresia_cliente2;
    private javax.swing.JSpinner mes_cli;
    private javax.swing.JTextField nombre_cli2;
    private javax.swing.JTextField telefono_cli2;
    // End of variables declaration//GEN-END:variables
}
