/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import Clases.Pelicula;
import Clases.Validaciones;
import javax.swing.JOptionPane;

public class Registrar_pelicula extends javax.swing.JFrame {

    String Cod_Pelicula = "";
    String titulo_pelicula = "";
    String Duracion = "";
    String Actores = "";
    String Clasificacion = "";
    String Anio_estreno = "";
    String Categoria = "";
    String Idioma = "";
    String Direcctores = "";

    public Registrar_pelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jBguardar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(604, 375));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel1.setText(" Codigo Pelicula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        jLabel2.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel2.setText("Titulo Pelicula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 20));

        jLabel3.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel3.setText("Actores:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 20));

        jLabel4.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel4.setText("Categoria:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 40));

        jLabel5.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel5.setText("Clasificacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 40));

        jLabel6.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel6.setText("Año estreno:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 40));

        jLabel7.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel7.setText("Idioma:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel8.setText("Directores:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 20));

        jLabel9.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jLabel9.setText("Duración:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));

        jTextField2.setText(" ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, -1));

        jComboBox2.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Acción", "Aventuras", "Ciencia Ficción", "Comedia", "Drama", "Fantasía", "Musical" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 130, -1));

        jComboBox3.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2021", "2022", "2023" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, -1));

        jTextField7.setText(" ");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 120, -1));

        jTextField8.setText(" ");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, -1));

        jTextField9.setText(" ");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 120, -1));

        jTextField10.setText(" ");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 120, -1));

        jLabel10.setFont(new java.awt.Font("Copperplate", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("INGRESE UNA PELICULA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 330, 40));

        jLabel11.setFont(new java.awt.Font("Copperplate", 3, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/claqueta.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 30, 30));

        jTextField12.setText(" ");
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, -1));

        jLabel12.setFont(new java.awt.Font("Copperplate", 3, 18)); // NOI18N
        jLabel12.setText("Registro de peliculas");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 20));

        jBguardar1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jBguardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardar-datos.png"))); // NOI18N
        jBguardar1.setText("GUARDAR");
        jBguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 150, 30));

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deshacer.png"))); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, 30));

        jComboBox4.setFont(new java.awt.Font("Copperplate", 3, 13)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion", "Apto para todo publico", "Mayor de 18 años", "Bajo supervision de adultos" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jBguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardar1ActionPerformed

        ObjectContainer BaseD = Db4o.openFile(Inicio.direccionBD);
        Crear_E(BaseD);
        Cerrar_BD(BaseD);
    }//GEN-LAST:event_jBguardar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Inicio vsar1 = new Inicio();
        vsar1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void asignarVariables(ObjectContainer basep) {
        Cod_Pelicula = jTextField2.getText();
        titulo_pelicula = jTextField10.getText();
        Duracion = jTextField8.getText();
        Actores = jTextField7.getText();
        Clasificacion = jComboBox4.getSelectedItem().toString();
        Anio_estreno = jComboBox3.getSelectedItem().toString();
        Categoria = jComboBox2.getSelectedItem().toString();
        Idioma = jTextField12.getText();
        Direcctores = jTextField9.getText();
    }

    public void Crear_E(ObjectContainer basep) {
        Validaciones miValidaciones = new Validaciones();
        if (validarCampos(basep)) {

            Pelicula Enuevo = new Pelicula(Cod_Pelicula, titulo_pelicula, Duracion, Actores, Clasificacion, Anio_estreno, Categoria, Idioma, Direcctores);

            if (Comprobar_Peliculas(basep, Cod_Pelicula) == 0) {
                basep.set(Enuevo);
                JOptionPane.showMessageDialog(null, "La pelicula se guardo correctamente");
                LimpiarCampos();
            } else {

                JOptionPane.showMessageDialog(null, "La pelicula ya existe");
            }
            jTextField2.setText("");

        }
        
    }

    public boolean validarCampos(ObjectContainer basep) {
        Validaciones miValidaciones = new Validaciones();
        asignarVariables(basep);
        boolean ban_confirmar = true;

        if (jTextField2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "INGRESE UN CODIGO");
            ban_confirmar = false;
        } else {
            if (!miValidaciones.validarid(Cod_Pelicula)) {
                JOptionPane.showMessageDialog(this, "CODIGO INVALIDO");
                ban_confirmar = false;
            }
        }
        
        if (jTextField10.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el titulo de la pelicula");
            ban_confirmar = false;
        } else {
            if (!miValidaciones.validarNomApe(titulo_pelicula)) {
                JOptionPane.showMessageDialog(this, "Titulo Pelicula invalido");
                ban_confirmar = false;
            }
        }
        
        

        return ban_confirmar;
    }

    public static int Comprobar_Peliculas(ObjectContainer basep, String IdUsuario) {

        Pelicula Ebuscar = new Pelicula(IdUsuario, null, null, null, null, null, null, null, null);

        ObjectSet result = basep.get(Ebuscar);

        return result.size();
    }

    public static void Cerrar_BD(ObjectContainer basep) {

        basep.close();
    }

    public void LimpiarCampos() {
        jTextField2.setText("");
        jTextField10.setText("");
        jTextField8.setText("");
        jTextField7.setText("");
        jComboBox4.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextField12.setText("");
        jTextField9.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
